# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8b05362b8f44ee54df3cde60e622e1ea5752942779178835c0c2742ac8ada04e3e110254845878747192248bb15beadccdceacc8501896ddeb7c26ab504fa41b

test:
  secret_key_base: 2a70f5bf6b71d7e398590980b75f7359a89842d1d84d0d2b0b660e0df60871c7767484f94630ad751288fa0d72a7a3aed96ee21d552d09b5a939b5dc947624e1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
